# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  condition:  ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    script: 'npm install -g firebase-tools'
    workingDirectory: '$(Agent.ToolsDirectory)'
  displayName: 'install firebase tools'

- task: CmdLine@2
  inputs:
    script: npm install
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'npm install '

- task: CmdLine@2
  inputs:
    script: npm run-script build
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'npm build '

- task: CmdLine@2
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    script: 'firebase deploy -P staging --token "$(AZURE_TOKEN)" -m "azure deploy"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'firebase publish -m "azure deploy"'