// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
// Data reducer scream types
export const SET_SCREAMS = "SET_SCREAMS";
export const SET_SCREAM = "SET_SCREAM";
export const EDIT_SCREAM = "EDIT_SCREAM";
export const SUBMIT_EDIT = "SUBMIT_EDIT";
export const LIKE_SCREAM = "LIKE_SCREAM";
export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
export const DELETE_SCREAM = "DELETE_SCREAM";
export const POST_SCREAM = "POST_SCREAM";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const SEARCH_SCREAMS = "SEARCH_SCREAM";
// Data reducer book types
export const SET_BOOKS = "SET_BOOKS";
export const SET_BOOK = "SET_BOOK";
export const EDIT_BOOK = "EDIT_BOOK";
export const SUBMIT_EDIT_BOOK = "SUBMIT_EDIT_BOOK";
export const LIKE_BOOK = "LIKE_BOOK";
export const UNLIKE_BOOK = "UNLIKE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const POST_BOOK = "POST_BOOK";
export const SUBMIT_COMMENT_BOOK = "SUBMIT_COMMENT_BOOK";
export const LOADING_BOOK = "LOADING_BOOK";
export const SEARCH_BOOKS = "SEARCH_BOOK";
